version: '3'

services:
  hello-world-container:
    build:
      context: ../
      dockerfile: ./docker-hello/hello-world.dockerfile
    container_name: hello-world
    networks:
      - hello-world-network

networks:
  hello-world-network:
    driver: bridge
