version: '3'

services:
  hello-world-container:
    build:
      context: ../../
      dockerfile: ./docker/hello/hello-world.dockerfile
      args:
        - CUSTOM_MESSAGE=This is the message passed from docker-compose
    container_name: hello-world
    networks:
      - hello-world-network

networks:
  hello-world-network:
    driver: bridge
